pesquisarPorTodosOsDadosNaoNulos1;
 SELECT * FROM estoques_view;

pesquisarPorTodosOsDadosNaoNulos2;
 ORDER BY estoque_material_dado_material_titulo, estoque_material_dado_material_descricao;

pesquisarTodosEdicaoAnoPublicaoAutorEditoraCategoriaPublicoFormatoStatu;
 SELECT * FROM estoques_combobox_view;