package com.live.adsfatene.biblioteca_publica.views.materiais;

import com.live.adsfatene.biblioteca_publica.models.AnoPublicacao;
import com.live.adsfatene.biblioteca_publica.models.Autor;
import com.live.adsfatene.biblioteca_publica.models.Categoria;
import com.live.adsfatene.biblioteca_publica.models.DadoMaterial;
import com.live.adsfatene.biblioteca_publica.models.Edicao;
import com.live.adsfatene.biblioteca_publica.models.Editora;
import com.live.adsfatene.biblioteca_publica.models.Formato;
import com.live.adsfatene.biblioteca_publica.models.Material;
import com.live.adsfatene.biblioteca_publica.models.Publico;
import javax.swing.JOptionPane;

public class EdicaoView extends javax.swing.JDialog {

    private final ListaView listaView;
    private Material material;

    EdicaoView(ListaView listaView, boolean modal) {
        super(listaView.getMateriaisController().getAplicacaoController().getAplicacaoView(), modal);
        initComponents();
        this.listaView = listaView;
        setLocationRelativeTo(this.listaView);
        jComboBoxEdicao.setEditable(true);
        jComboBoxAnoPublicacao.setEditable(true);
        jComboBoxAutor.setEditable(true);
        jComboBoxEditora.setEditable(true);
        jComboBoxCategoria.setEditable(true);
        jComboBoxPublico.setEditable(true);
        jComboBoxFormato.setEditable(true);
    }

    @Override
    public void setVisible(boolean flag) {
        if (flag) {
            jButtonLimparActionPerformed(null);
            setLocationRelativeTo(this.listaView);
        }
        listaView.getjToggleButtonEdicao().setSelected(flag);
        super.setVisible(flag);
    }

    public void atualizar(Material material) {
        jComboBoxEdicao.removeAllItems();
        jComboBoxAnoPublicacao.removeAllItems();
        jComboBoxAutor.removeAllItems();
        jComboBoxEditora.removeAllItems();
        jComboBoxCategoria.removeAllItems();
        jComboBoxPublico.removeAllItems();
        jComboBoxFormato.removeAllItems();


        jTextFieldTitulo.setText(material.getDadoMaterial().getTitulo());
        jTextFieldDescricao.setText(material.getDadoMaterial().getDescricao());

        for (Edicao edicao : listaView.getMaterialComboBox().getEdicoes()) {
            jComboBoxEdicao.addItem(edicao);
        }
        jComboBoxEdicao.setSelectedItem(material.getDadoMaterial().getEdicao());

        for (AnoPublicacao anoPublicacao : listaView.getMaterialComboBox().getAnosPublicacoes()) {
            jComboBoxAnoPublicacao.addItem(anoPublicacao);
        }
        jComboBoxAnoPublicacao.setSelectedItem(material.getDadoMaterial().getAnoPublicacao());

        for (Autor autor : listaView.getMaterialComboBox().getAutores()) {
            jComboBoxAutor.addItem(autor);
        }
        jComboBoxAutor.setSelectedItem(material.getDadoMaterial().getAutor());

        for (Editora editora : listaView.getMaterialComboBox().getEditoras()) {
            jComboBoxEditora.addItem(editora);
        }
        jComboBoxEditora.setSelectedItem(material.getDadoMaterial().getEditora());

        for (Categoria categoria : listaView.getMaterialComboBox().getCategorias()) {
            jComboBoxCategoria.addItem(categoria);
        }
        jComboBoxCategoria.setSelectedItem(material.getDadoMaterial().getCategoria());

        for (Publico publico : listaView.getMaterialComboBox().getPublicos()) {
            jComboBoxPublico.addItem(publico);
        }
        jComboBoxPublico.setSelectedItem(material.getDadoMaterial().getPublico());

        for (Formato formato : listaView.getMaterialComboBox().getFormatos()) {
            jComboBoxFormato.addItem(formato);
        }
        jComboBoxFormato.setSelectedItem(material.getFormato());

        jTextFieldInformacao.setText(material.getInformacao());
        jTextFieldLocalizacao.setText(material.getLocalLogicoFisico());

        this.material = material;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxFormato = new javax.swing.JComboBox();
        jTextFieldTitulo = new javax.swing.JTextField();
        jComboBoxPublico = new javax.swing.JComboBox();
        jComboBoxCategoria = new javax.swing.JComboBox();
        jLabelCategoria = new javax.swing.JLabel();
        jLabelEditora = new javax.swing.JLabel();
        jLabelFormato = new javax.swing.JLabel();
        jLabelPublico = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jComboBoxEdicao = new javax.swing.JComboBox();
        jLabelEdicao = new javax.swing.JLabel();
        jLabelAnoPublicacao = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jComboBoxEditora = new javax.swing.JComboBox();
        jComboBoxAnoPublicacao = new javax.swing.JComboBox();
        jComboBoxAutor = new javax.swing.JComboBox();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jTextFieldLocalizacao = new javax.swing.JTextField();
        jLabelLocalizacao = new javax.swing.JLabel();
        jLabelInformacao = new javax.swing.JLabel();
        jTextFieldInformacao = new javax.swing.JTextField();

        setTitle("Edição");
        setResizable(false);

        jComboBoxFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormatoActionPerformed(evt);
            }
        });

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });

        jLabelCategoria.setText("Categoria");

        jLabelEditora.setText("Editora");

        jLabelFormato.setText("Formato");

        jLabelPublico.setText("Publico");

        jLabelDescricao.setText("Descrição");

        jLabelEdicao.setText("Edição");

        jLabelAnoPublicacao.setText("Ano de Publicação");

        jLabelAutor.setText("Autor");

        jComboBoxAnoPublicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnoPublicacaoActionPerformed(evt);
            }
        });

        jLabelTitulo.setText("Título");

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabelLocalizacao.setText("Localização");

        jLabelInformacao.setText("Informação");

        jTextFieldInformacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInformacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLocalizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelInformacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDescricao)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelEdicao)
                    .addComponent(jLabelAnoPublicacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAutor)
                    .addComponent(jLabelEditora)
                    .addComponent(jLabelCategoria)
                    .addComponent(jLabelPublico)
                    .addComponent(jLabelFormato))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldDescricao)
                        .addComponent(jComboBoxEdicao, 0, 312, Short.MAX_VALUE)
                        .addComponent(jComboBoxAnoPublicacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxAutor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxEditora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxPublico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxFormato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                        .addComponent(jTextFieldInformacao)
                        .addComponent(jTextFieldLocalizacao)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescricao)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdicao)
                    .addComponent(jComboBoxEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnoPublicacao)
                    .addComponent(jComboBoxAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutor)
                    .addComponent(jComboBoxAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditora)
                    .addComponent(jComboBoxEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategoria)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPublico)
                    .addComponent(jComboBoxPublico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFormato)
                    .addComponent(jComboBoxFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInformacao)
                    .addComponent(jTextFieldInformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocalizacao)
                    .addComponent(jTextFieldLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtualizar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jComboBoxAnoPublicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnoPublicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAnoPublicacaoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldTitulo.setText(material.getDadoMaterial().getTitulo());
        jTextFieldDescricao.setText(material.getDadoMaterial().getDescricao());
        jComboBoxEdicao.setSelectedItem(material.getDadoMaterial().getEdicao());
        jComboBoxAnoPublicacao.setSelectedItem(material.getDadoMaterial().getAnoPublicacao());
        jComboBoxAutor.setSelectedItem(material.getDadoMaterial().getAutor());
        jComboBoxEditora.setSelectedItem(material.getDadoMaterial().getEditora());
        jComboBoxCategoria.setSelectedItem(material.getDadoMaterial().getCategoria());
        jComboBoxPublico.setSelectedItem(material.getDadoMaterial().getPublico());
        jComboBoxFormato.setSelectedItem(material.getFormato());
        jTextFieldInformacao.setText(material.getInformacao());
        jTextFieldLocalizacao.setText(material.getLocalLogicoFisico());
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jComboBoxFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFormatoActionPerformed
    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        Material material = new Material();
        DadoMaterial dadoMaterial = new DadoMaterial();
        dadoMaterial.setTitulo(jTextFieldTitulo.getText());
        dadoMaterial.setDescricao(jTextFieldDescricao.getText());

        Edicao edicao;
        if (jComboBoxEdicao.getSelectedItem() instanceof Edicao) {
            edicao = (Edicao) jComboBoxEdicao.getSelectedItem();
        } else {
            edicao = new Edicao();
            edicao.setNumero(Integer.valueOf(jComboBoxEdicao.getSelectedItem().toString()));
        }
        dadoMaterial.setEdicao(edicao);

        AnoPublicacao anoPublicacao;
        if (jComboBoxAnoPublicacao.getSelectedItem() instanceof AnoPublicacao) {
            anoPublicacao = (AnoPublicacao) jComboBoxAnoPublicacao.getSelectedItem();
        } else {
            anoPublicacao = new AnoPublicacao();
            anoPublicacao.setAno(Integer.valueOf(jComboBoxAnoPublicacao.getSelectedItem().toString()));
        }
        dadoMaterial.setAnoPublicacao(anoPublicacao);

        Autor autor;
        if (jComboBoxAutor.getSelectedItem() instanceof Autor) {
            autor = (Autor) jComboBoxAutor.getSelectedItem();
        } else {
            autor = new Autor();
            autor.setNome(jComboBoxAutor.getSelectedItem().toString());
        }
        dadoMaterial.setAutor(autor);

        Editora editora;
        if (jComboBoxEditora.getSelectedItem() instanceof Editora) {
            editora = (Editora) jComboBoxEditora.getSelectedItem();
        } else {
            editora = new Editora();
            editora.setNome(jComboBoxEditora.getSelectedItem().toString());
        }
        dadoMaterial.setEditora(editora);

        Categoria categoria;
        if (jComboBoxCategoria.getSelectedItem() instanceof Categoria) {
            categoria = (Categoria) jComboBoxCategoria.getSelectedItem();
        } else {
            categoria = new Categoria();
            categoria.setNome(jComboBoxCategoria.getSelectedItem().toString());
        }
        dadoMaterial.setCategoria(categoria);

        Publico publico;
        if (jComboBoxPublico.getSelectedItem() instanceof Publico) {
            publico = (Publico) jComboBoxPublico.getSelectedItem();
        } else {
            publico = new Publico();
            publico.setNome(jComboBoxPublico.getSelectedItem().toString());
        }
        dadoMaterial.setPublico(publico);

        dadoMaterial.setCodigo(this.material.getDadoMaterial().getCodigo());
        material.setDadoMaterial(dadoMaterial);

        Formato formato;
        if (jComboBoxFormato.getSelectedItem() instanceof Formato) {
            formato = (Formato) jComboBoxFormato.getSelectedItem();
        } else {
            formato = new Formato();
            formato.setNome(jComboBoxFormato.getSelectedItem().toString());
        }
        material.setFormato(formato);

        material.setInformacao(jTextFieldInformacao.getText());
        material.setLocalLogicoFisico(jTextFieldLocalizacao.getText());
        material.setCodigo(this.material.getCodigo());

        if (!this.material.ehIgual(material)) {
            this.material = material;
            listaView.getMateriaisController().atualizar(this.material);
        } else {
            JOptionPane.showMessageDialog(this, "material nao editado.", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jTextFieldInformacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInformacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInformacaoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JComboBox jComboBoxAnoPublicacao;
    private javax.swing.JComboBox jComboBoxAutor;
    private javax.swing.JComboBox jComboBoxCategoria;
    private javax.swing.JComboBox jComboBoxEdicao;
    private javax.swing.JComboBox jComboBoxEditora;
    private javax.swing.JComboBox jComboBoxFormato;
    private javax.swing.JComboBox jComboBoxPublico;
    private javax.swing.JLabel jLabelAnoPublicacao;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelEdicao;
    private javax.swing.JLabel jLabelEditora;
    private javax.swing.JLabel jLabelFormato;
    private javax.swing.JLabel jLabelInformacao;
    private javax.swing.JLabel jLabelLocalizacao;
    private javax.swing.JLabel jLabelPublico;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldInformacao;
    private javax.swing.JTextField jTextFieldLocalizacao;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
