package com.live.adsfatene.biblioteca_publica.views.materiais;

import com.live.adsfatene.biblioteca_publica.controllers.MateriaisController;
import com.live.adsfatene.biblioteca_publica.models.Material;
import com.live.adsfatene.biblioteca_publica.models.util.MaterialComboBox;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;

public class ListaView extends javax.swing.JPanel {

    private final MateriaisController materiaisController;
    private final DefaultTableModel dtm;
    private final List<Material> materiais;
    private final CadastroView cadastroView;
    private final FiltroView filtroView;
    private final EdicaoView edicaoView;
    private MaterialComboBox materialComboBox;
    private final SimpleDateFormat sdf;
    
    public ListaView(MateriaisController materiaisController) {
        initComponents();
        this.materiaisController = materiaisController;
        dtm = (DefaultTableModel) jTableLista.getModel();
        materiais = new LinkedList<>();
        cadastroView = new CadastroView(this, false);
        filtroView = new FiltroView(this, false);
        edicaoView = new EdicaoView(this, false);
        sdf = new SimpleDateFormat("dd/MM/YYYY");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarAcoes = new javax.swing.JToolBar();
        jToggleButtonFiltro = new javax.swing.JToggleButton();
        jToggleButtonEdicao = new javax.swing.JToggleButton();
        jToggleButtonCadastro = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLista = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBarAcoes.setRollover(true);

        jToggleButtonFiltro.setText("Filtro");
        jToggleButtonFiltro.setFocusable(false);
        jToggleButtonFiltro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonFiltro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonFiltroActionPerformed(evt);
            }
        });
        jToolBarAcoes.add(jToggleButtonFiltro);

        jToggleButtonEdicao.setText("Edição");
        jToggleButtonEdicao.setFocusable(false);
        jToggleButtonEdicao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonEdicao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEdicaoActionPerformed(evt);
            }
        });
        jToolBarAcoes.add(jToggleButtonEdicao);

        jToggleButtonCadastro.setText("Cadastro");
        jToggleButtonCadastro.setFocusable(false);
        jToggleButtonCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonCadastro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCadastroActionPerformed(evt);
            }
        });
        jToolBarAcoes.add(jToggleButtonCadastro);

        add(jToolBarAcoes, java.awt.BorderLayout.PAGE_START);

        jTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material", "Codigo", "Titulo", "Descrição", "Edição", "Ano de Publicação", "Autor", "Editora", "Categoria", "Publico", "Formato", "Informação", "Locaização", "Data de Cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableListaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableListaMousePressed(evt);
            }
        });
        jTableLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableListaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLista);
        jTableLista.getColumnModel().getColumn(0).setMinWidth(0);
        jTableLista.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTableLista.getColumnModel().getColumn(0).setMaxWidth(0);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCadastroActionPerformed
        materiaisController.cadastrar();
    }//GEN-LAST:event_jToggleButtonCadastroActionPerformed

    private void jToggleButtonFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonFiltroActionPerformed
        materiaisController.filtrar(new Material());
    }//GEN-LAST:event_jToggleButtonFiltroActionPerformed

    private void jTableListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaMousePressed
    }//GEN-LAST:event_jTableListaMousePressed

    private void jTableListaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListaKeyPressed
    }//GEN-LAST:event_jTableListaKeyPressed

    private void jToggleButtonEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEdicaoActionPerformed
        if (jTableLista.getSelectedRowCount() > 0) {
            materiaisController.editar((Material) jTableLista.getValueAt(jTableLista.getSelectedRow(), 0));
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Material.", "Erro", JOptionPane.ERROR_MESSAGE);
            jToggleButtonEdicao.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButtonEdicaoActionPerformed

    private void jTableListaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaMouseEntered
    }//GEN-LAST:event_jTableListaMouseEntered

    private void jTableListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaMouseClicked
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1 && jToggleButtonEdicao.isSelected()) {
            materiaisController.editar((Material) jTableLista.getValueAt(jTableLista.getSelectedRow(), 0));
        }
    }//GEN-LAST:event_jTableListaMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLista;
    private javax.swing.JToggleButton jToggleButtonCadastro;
    private javax.swing.JToggleButton jToggleButtonEdicao;
    private javax.swing.JToggleButton jToggleButtonFiltro;
    private javax.swing.JToolBar jToolBarAcoes;
    // End of variables declaration//GEN-END:variables

    public void atualizar(List<Material> materiais, MaterialComboBox materialComboBox) {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }

        this.materiais.clear();

        this.materiais.addAll(materiais);
        this.materialComboBox = materialComboBox;

        for (Material material : this.materiais) {
            dtm.addRow(new Object[dtm.getColumnCount()]);
            int i = 0;
            dtm.setValueAt(material, dtm.getRowCount() - 1, i++);
            dtm.setValueAt(material.getCodigo(), dtm.getRowCount() - 1, i++);
            dtm.setValueAt(material.getDadoMaterial().getTitulo(), dtm.getRowCount() - 1, i++);
            dtm.setValueAt(material.getDadoMaterial().getDescricao(), dtm.getRowCount() - 1, i++);
            dtm.setValueAt(material.getDadoMaterial().getEdicao(), dtm.getRowCount() - 1, i++);
            dtm.setValueAt(material.getDadoMaterial().getAnoPublicacao(), dtm.getRowCount() - 1, i++);
            dtm.setValueAt(material.getDadoMaterial().getAutor(), dtm.getRowCount() - 1, i++);
            dtm.setValueAt(material.getDadoMaterial().getEditora().getNome(), dtm.getRowCount() - 1, i++);
            dtm.setValueAt(material.getDadoMaterial().getCategoria().getNome(), dtm.getRowCount() - 1, i++);
            dtm.setValueAt(material.getDadoMaterial().getPublico().getNome(), dtm.getRowCount() - 1, i++);
            dtm.setValueAt(material.getFormato().getNome(), dtm.getRowCount() - 1, i++);
            dtm.setValueAt(material.getInformacao(), dtm.getRowCount() - 1, i++);
            dtm.setValueAt(material.getLocalLogicoFisico(), dtm.getRowCount() - 1, i++);
            dtm.setValueAt( sdf.format(material.getDataHoraCadastro().getTime()), dtm.getRowCount() - 1, i++);
        }
    }

    public MateriaisController getMateriaisController() {
        return materiaisController;
    }

    public JToggleButton getjToggleButtonCadastro() {
        return jToggleButtonCadastro;
    }

    public JToggleButton getjToggleButtonFiltro() {
        return jToggleButtonFiltro;
    }

    public JToggleButton getjToggleButtonEdicao() {
        return jToggleButtonEdicao;
    }

    public FiltroView getFiltroView() {
        return filtroView;
    }

    public EdicaoView getEdicaoView() {
        return edicaoView;
    }

    public CadastroView getCadastroView() {
        return cadastroView;
    }

    public MaterialComboBox getMaterialComboBox() {
        return materialComboBox;
    }
}