package com.live.ads21fatene.biblioteca_publica.views.materiais;

import com.live.ads21fatene.biblioteca_publica.controllers.MateriaisController;
import com.live.ads21fatene.biblioteca_publica.models.Material;
import com.live.ads21fatene.biblioteca_publica.views.AplicacaoView;
import java.util.LinkedList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class ListaPesquisaView extends javax.swing.JPanel {

    private final MateriaisController materiaisController;
    private final DefaultTableModel dtm;
    private final List<Material> materiais;
    private final FormularioPesquisaView formularioPesquisaJDialog;

    public ListaPesquisaView(MateriaisController materiaisController) {
        initComponents();
        this.materiaisController = materiaisController;
        dtm = (DefaultTableModel) jTableLista.getModel();
        materiais = new LinkedList<>();
        formularioPesquisaJDialog = new FormularioPesquisaView(this, false);
    }

    @Override
    public void setVisible(boolean aFlag) {
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        materiais.clear();
        super.setVisible(aFlag);
        formularioPesquisaJDialog.setVisible(aFlag);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLista = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ));
        jScrollPane1.setViewportView(jTableLista);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLista;
    // End of variables declaration//GEN-END:variables

    public void atualizar(List<Material> materiais) {
        this.materiais.addAll(materiais);
        for (Material material : this.materiais) {
            dtm.addRow(new Object[dtm.getColumnCount()]);
            dtm.setValueAt(material.getCodigo(), dtm.getRowCount() - 1, 0);
            dtm.setValueAt(material.getDadoMaterial().getTitulo(), dtm.getRowCount() - 1, 1);
            dtm.setValueAt(material.getDadoMaterial().getDescricao(), dtm.getRowCount() - 1, 2);
            dtm.setValueAt(material.getDadoMaterial().getEdicao(), dtm.getRowCount() - 1, 3);
            dtm.setValueAt(material.getDadoMaterial().getAnoPublicacao(), dtm.getRowCount() - 1, 4);
            dtm.setValueAt(material.getDadoMaterial().getAutor(), dtm.getRowCount() - 1, 5);
            dtm.setValueAt(material.getDadoMaterial().getEditora().getNome(), dtm.getRowCount() - 1, 6);
            dtm.setValueAt(material.getDadoMaterial().getCategoria().getNome(), dtm.getRowCount() - 1, 7);
            dtm.setValueAt(material.getDadoMaterial().getPublico().getNome(), dtm.getRowCount() - 1, 8);
            dtm.setValueAt(material.getFormato().getNome(), dtm.getRowCount() - 1, 9);
            dtm.setValueAt(material.getInformacao(), dtm.getRowCount() - 1, 10);
            dtm.setValueAt(material.getLocalLogicoFisico(), dtm.getRowCount() - 1, 11);
            dtm.setValueAt(material.getDataHoraCadastro(), dtm.getRowCount() - 1, 12);
        }
    }

    public MateriaisController getMateriaisController() {
        return materiaisController;
    }
}