package com.live.ads21fatene.biblioteca_publica.views.materiais;

import com.live.ads21fatene.biblioteca_publica.controllers.MateriaisController;
import com.live.ads21fatene.biblioteca_publica.models.Material;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;

public class ListaView extends javax.swing.JPanel {

    private final MateriaisController materiaisController;
    private final DefaultTableModel dtm;
    private final List<Material> materiais;
    private final CadastroView cadastroView;
    private final FiltroView filtroView;
    private final EdicaoView edicaoView;

    public ListaView(MateriaisController materiaisController) {
        initComponents();
        this.materiaisController = materiaisController;
        dtm = (DefaultTableModel) jTableLista.getModel();
        materiais = new LinkedList<>();
        cadastroView = new CadastroView(this, false);
        filtroView = new FiltroView(this, false);
        edicaoView = new EdicaoView(this, false);
    }

    @Override
    public void setVisible(boolean aFlag) {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        materiais.clear();
        super.setVisible(aFlag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarAcoes = new javax.swing.JToolBar();
        jToggleButtonFiltro = new javax.swing.JToggleButton();
        jToggleButtonEdicao = new javax.swing.JToggleButton();
        jToggleButtonCadastro = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLista = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBarAcoes.setRollover(true);

        jToggleButtonFiltro.setText("Filtro");
        jToggleButtonFiltro.setFocusable(false);
        jToggleButtonFiltro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonFiltro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonFiltroActionPerformed(evt);
            }
        });
        jToolBarAcoes.add(jToggleButtonFiltro);

        jToggleButtonEdicao.setText("Edição");
        jToggleButtonEdicao.setFocusable(false);
        jToggleButtonEdicao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonEdicao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEdicaoActionPerformed(evt);
            }
        });
        jToolBarAcoes.add(jToggleButtonEdicao);

        jToggleButtonCadastro.setText("Cadastro");
        jToggleButtonCadastro.setFocusable(false);
        jToggleButtonCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonCadastro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCadastroActionPerformed(evt);
            }
        });
        jToolBarAcoes.add(jToggleButtonCadastro);

        add(jToolBarAcoes, java.awt.BorderLayout.PAGE_START);

        jTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableListaMousePressed(evt);
            }
        });
        jTableLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableListaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLista);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCadastroActionPerformed
        cadastroView.setVisible(jToggleButtonCadastro.isSelected());
    }//GEN-LAST:event_jToggleButtonCadastroActionPerformed

    private void jToggleButtonFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonFiltroActionPerformed
        filtroView.setVisible(jToggleButtonFiltro.isSelected());
    }//GEN-LAST:event_jToggleButtonFiltroActionPerformed

    private void jTableListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaMousePressed
    }//GEN-LAST:event_jTableListaMousePressed

    private void jTableListaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListaKeyPressed
    }//GEN-LAST:event_jTableListaKeyPressed

    private void jToggleButtonEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEdicaoActionPerformed
        edicaoView.setVisible(jToggleButtonEdicao.isSelected());
    }//GEN-LAST:event_jToggleButtonEdicaoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLista;
    private javax.swing.JToggleButton jToggleButtonCadastro;
    private javax.swing.JToggleButton jToggleButtonEdicao;
    private javax.swing.JToggleButton jToggleButtonFiltro;
    private javax.swing.JToolBar jToolBarAcoes;
    // End of variables declaration//GEN-END:variables

    public void atualizar(List<Material> materiais) {
        this.materiais.addAll(materiais);
        for (Material material : this.materiais) {
            dtm.addRow(new Object[dtm.getColumnCount()]);
            dtm.setValueAt(material.getCodigo(), dtm.getRowCount() - 1, 0);
            dtm.setValueAt(material.getDadoMaterial().getTitulo(), dtm.getRowCount() - 1, 1);
            dtm.setValueAt(material.getDadoMaterial().getDescricao(), dtm.getRowCount() - 1, 2);
            dtm.setValueAt(material.getDadoMaterial().getEdicao(), dtm.getRowCount() - 1, 3);
            dtm.setValueAt(material.getDadoMaterial().getAnoPublicacao(), dtm.getRowCount() - 1, 4);
            dtm.setValueAt(material.getDadoMaterial().getAutor(), dtm.getRowCount() - 1, 5);
            dtm.setValueAt(material.getDadoMaterial().getEditora().getNome(), dtm.getRowCount() - 1, 6);
            dtm.setValueAt(material.getDadoMaterial().getCategoria().getNome(), dtm.getRowCount() - 1, 7);
            dtm.setValueAt(material.getDadoMaterial().getPublico().getNome(), dtm.getRowCount() - 1, 8);
            dtm.setValueAt(material.getFormato().getNome(), dtm.getRowCount() - 1, 9);
            dtm.setValueAt(material.getInformacao(), dtm.getRowCount() - 1, 10);
            dtm.setValueAt(material.getLocalLogicoFisico(), dtm.getRowCount() - 1, 11);
            dtm.setValueAt(material.getDataHoraCadastro(), dtm.getRowCount() - 1, 12);
        }
    }

    public MateriaisController getMateriaisController() {
        return materiaisController;
    }

    public JToggleButton getjToggleButtonCadastro() {
        return jToggleButtonCadastro;
    }

    public JToggleButton getjToggleButtonFiltro() {
        return jToggleButtonFiltro;
    }

    public JToggleButton getjToggleButtonEdicao() {
        return jToggleButtonEdicao;
    }
}