package com.live.adsfatene.biblioteca_publica.views.emprestimos_irrecuperaveis;

import com.live.adsfatene.biblioteca_publica.controllers.EmprestimosIrrecuperaveisController;

public class PesquisaView extends javax.swing.JPanel {

    private final EmprestimosIrrecuperaveisController estoquesIrrecuperaveisController;

    public PesquisaView(EmprestimosIrrecuperaveisController estoquesIrrecuperaveisController) {
        this.estoquesIrrecuperaveisController = estoquesIrrecuperaveisController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMateriais = new javax.swing.JLabel();

        jLabelMateriais.setText("Emprestimos Irrecuperaveis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabelMateriais)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabelMateriais)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMateriais;
    // End of variables declaration//GEN-END:variables
}
