package com.live.adsfatene.biblioteca_publica.views.emprestimos;

import javax.swing.table.DefaultTableModel;
import com.live.adsfatene.biblioteca_publica.models.Cidadao;
import com.live.adsfatene.biblioteca_publica.models.Emprestimo;
import com.live.adsfatene.biblioteca_publica.models.EmprestimoEstoque;
import com.live.adsfatene.biblioteca_publica.models.Estoque;
import java.text.ParseException;
import java.util.Calendar;
import java.util.LinkedList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

public class CadastroView extends javax.swing.JDialog {

    private final ListaView listaView;
    private final DefaultTableModel dtm;
    private Cidadao cidadao;

    CadastroView(ListaView listaView, boolean modal) {
        super(listaView.getEmprestimosController().getAplicacaoController().getAplicacaoView(), modal);
        initComponents();
        this.listaView = listaView;
        dtm = (DefaultTableModel) jTableEstoques.getModel();
    }

    @Override
    public void setVisible(boolean flag) {
        if (flag) {
            setLocationRelativeTo(listaView.getEmprestimosController().getAplicacaoController().getAplicacaoView());
        }
        listaView.getjToggleButtonCadastro().setSelected(flag);
        super.setVisible(flag);
    }

    public void alterarCidadao(Cidadao cidadao) {
        this.cidadao = cidadao;
        jTextFieldCidadao.setText(this.cidadao.toString());
    }

    public void atualizar() {
        jButtonLimparActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonCancelar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonEmprestar = new javax.swing.JButton();
        jButtonRemoverEstoque = new javax.swing.JButton();
        jButtonAdicionarEstoque = new javax.swing.JButton();
        jLabeCidadao = new javax.swing.JLabel();
        jTextFieldCidadao = new javax.swing.JTextField();
        jLabelEstoques = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEstoques = new javax.swing.JTable();
        jLabelDataHoraDevolucaoPrevista = new javax.swing.JLabel();
        jTextFieldDataHoraDevolucaoPrevista = new javax.swing.JTextField();
        jTextFieldDataHoraEmprestado = new javax.swing.JTextField();
        jLabelDataHoraEmprestado = new javax.swing.JLabel();
        jToggleButtonAlterarCidadao = new javax.swing.JToggleButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Cadastro");
        setResizable(false);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonEmprestar.setText("Emprestar");
        jButtonEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmprestarActionPerformed(evt);
            }
        });

        jButtonRemoverEstoque.setText("-");
        jButtonRemoverEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverEstoqueActionPerformed(evt);
            }
        });

        jButtonAdicionarEstoque.setText("+");
        jButtonAdicionarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarEstoqueActionPerformed(evt);
            }
        });

        jLabeCidadao.setText("Cidadão");

        jTextFieldCidadao.setEditable(false);
        jTextFieldCidadao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadaoActionPerformed(evt);
            }
        });

        jLabelEstoques.setText("Estoques");

        jTableEstoques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estoque", "Titulo", "Formato", "Localização"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableEstoques);
        jTableEstoques.getColumnModel().getColumn(0).setMinWidth(0);
        jTableEstoques.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTableEstoques.getColumnModel().getColumn(0).setMaxWidth(0);

        jLabelDataHoraDevolucaoPrevista.setText("Data/Hora Devolução Prevista");

        jTextFieldDataHoraDevolucaoPrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataHoraDevolucaoPrevistaActionPerformed(evt);
            }
        });

        jTextFieldDataHoraEmprestado.setEditable(false);
        jTextFieldDataHoraEmprestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataHoraEmprestadoActionPerformed(evt);
            }
        });

        jLabelDataHoraEmprestado.setText("Data/Hora Emprestado");

        jToggleButtonAlterarCidadao.setText("Alterar Cidadão");
        jToggleButtonAlterarCidadao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAlterarCidadaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelEstoques, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAdicionarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonRemoverEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextFieldCidadao)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelDataHoraDevolucaoPrevista)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDataHoraDevolucaoPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabeCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButtonAlterarCidadao))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelDataHoraEmprestado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDataHoraEmprestado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEmprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeCidadao)
                    .addComponent(jToggleButtonAlterarCidadao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstoques)
                    .addComponent(jButtonAdicionarEstoque)
                    .addComponent(jButtonRemoverEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataHoraEmprestado)
                    .addComponent(jTextFieldDataHoraEmprestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataHoraDevolucaoPrevista)
                    .addComponent(jTextFieldDataHoraDevolucaoPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonEmprestar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        cidadao = null;
        jTextFieldCidadao.setText("");
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        jTextFieldDataHoraEmprestado.setText(listaView.getSdf().format(Calendar.getInstance().getTime()));
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmprestarActionPerformed
        if (cidadao == null) {
            JOptionPane.showMessageDialog(this, "cidadao obrigatorio", "aviso", JOptionPane.WARNING_MESSAGE);
        } else if (dtm.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "estoques obrigatorio", "aviso", JOptionPane.WARNING_MESSAGE);
        } else if (jTextFieldDataHoraDevolucaoPrevista.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "data/hora devolucao prevista obrigatorio", "aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Emprestimo emprestimo = new Emprestimo();
                emprestimo.setCidadao(cidadao);
                emprestimo.setDataHoraEmprestato(Calendar.getInstance());
                emprestimo.getDataHoraEmprestato().setTime(listaView.getSdf().parse(jTextFieldDataHoraEmprestado.getText()));
                emprestimo.setDataHoraDevolucaoPrevista(Calendar.getInstance());
                emprestimo.getDataHoraDevolucaoPrevista().setTime(listaView.getSdf().parse(jTextFieldDataHoraDevolucaoPrevista.getText()));
                
                emprestimo.setEmprestimosEstoques(new LinkedList<EmprestimoEstoque>());
                for(int i = 0; i < dtm.getRowCount(); i++){
                    EmprestimoEstoque emprestimoEstoque = new EmprestimoEstoque();
                    emprestimoEstoque.setEstoque((Estoque) dtm.getValueAt(i, 0));
                    emprestimo.getEmprestimosEstoques().add(emprestimoEstoque);
                }
                listaView.getEmprestimosController().salvar(emprestimo);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "aviso", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonEmprestarActionPerformed

    private void jButtonRemoverEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverEstoqueActionPerformed
        while (jTableEstoques.getSelectedRowCount() > 0) {
            dtm.removeRow(jTableEstoques.getSelectedRow());
        }
    }//GEN-LAST:event_jButtonRemoverEstoqueActionPerformed

    private void jButtonAdicionarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarEstoqueActionPerformed
        listaView.getEmprestimosController().adicionarEstoque(true);
    }//GEN-LAST:event_jButtonAdicionarEstoqueActionPerformed

    private void jTextFieldCidadaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadaoActionPerformed
    }//GEN-LAST:event_jTextFieldCidadaoActionPerformed

    private void jTextFieldDataHoraDevolucaoPrevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataHoraDevolucaoPrevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataHoraDevolucaoPrevistaActionPerformed

    private void jTextFieldDataHoraEmprestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataHoraEmprestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataHoraEmprestadoActionPerformed

    public JToggleButton getjToggleButtonAlterarCidadao() {
        return jToggleButtonAlterarCidadao;
    }

    public Cidadao getCidadao() {
        return cidadao;
    }

    public JTextField getjTextFieldCidadao() {
        return jTextFieldCidadao;
    }

    public void setCidadao(Cidadao cidadao) {
        this.cidadao = cidadao;
    }

    public DefaultTableModel getDtm() {
        return dtm;
    }

    public JButton getjButtonAdicionarEstoque() {
        return jButtonAdicionarEstoque;
    }

    private void jToggleButtonAlterarCidadaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAlterarCidadaoActionPerformed
        listaView.getEmprestimosController().alterarCidadao(true);
    }//GEN-LAST:event_jToggleButtonAlterarCidadaoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarEstoque;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEmprestar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonRemoverEstoque;
    private javax.swing.JLabel jLabeCidadao;
    private javax.swing.JLabel jLabelDataHoraDevolucaoPrevista;
    private javax.swing.JLabel jLabelDataHoraEmprestado;
    private javax.swing.JLabel jLabelEstoques;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableEstoques;
    private javax.swing.JTextField jTextFieldCidadao;
    private javax.swing.JTextField jTextFieldDataHoraDevolucaoPrevista;
    private javax.swing.JTextField jTextFieldDataHoraEmprestado;
    private javax.swing.JToggleButton jToggleButtonAlterarCidadao;
    // End of variables declaration//GEN-END:variables
}
