package com.live.adsfatene.biblioteca_publica.views.emprestimos;

import com.live.adsfatene.biblioteca_publica.views.estoques.*;
import com.live.adsfatene.biblioteca_publica.models.AnoPublicacao;
import com.live.adsfatene.biblioteca_publica.models.Autor;
import com.live.adsfatene.biblioteca_publica.models.Categoria;
import com.live.adsfatene.biblioteca_publica.models.DadoMaterial;
import com.live.adsfatene.biblioteca_publica.models.Edicao;
import com.live.adsfatene.biblioteca_publica.models.Editora;
import com.live.adsfatene.biblioteca_publica.models.Estoque;
import com.live.adsfatene.biblioteca_publica.models.Formato;
import com.live.adsfatene.biblioteca_publica.models.Material;
import com.live.adsfatene.biblioteca_publica.models.Publico;
import com.live.adsfatene.biblioteca_publica.models.Statu;

public class FiltroView extends javax.swing.JDialog {

//    private final ListaView listaView;

    FiltroView(ListaView listaView, boolean modal) {
//        super(listaView.getEstoquesController().getAplicacaoController().getAplicacaoView(), modal);
//        initComponents();
//        this.listaView = listaView;
    }

    @Override
    public void setVisible(boolean flag) {
//        if (flag) {
//            jButtonLimparActionPerformed(null);
//            if (!isVisible()) {
//                setLocationRelativeTo(listaView.getEstoquesController().getAplicacaoController().getAplicacaoView());
//            }
//        }
//        listaView.getjToggleButtonFiltro().setSelected(flag);
//        super.setVisible(flag);
    }

    public void atualizar() {
//        jComboBoxCodigo.removeAllItems();
//        jComboBoxAnoPublicacao.removeAllItems();
//        jComboBoxAutor.removeAllItems();
//        jComboBoxEditora.removeAllItems();
//        jComboBoxCategoria.removeAllItems();
//        jComboBoxPublico.removeAllItems();
//        jComboBoxFormato.removeAllItems();
//        jComboBoxStatu.removeAllItems();
//
//        jComboBoxCodigo.addItem("Todos");
//        for (Edicao edicao : listaView.getEstoqueComboBox().getMaterialComboBox().getEdicoes()) {
//            jComboBoxCodigo.addItem(edicao);
//        }
//
//        jComboBoxAnoPublicacao.addItem("Todos");
//        for (AnoPublicacao anoPublicacao : listaView.getEstoqueComboBox().getMaterialComboBox().getAnosPublicacoes()) {
//            jComboBoxAnoPublicacao.addItem(anoPublicacao);
//        }
//
//        jComboBoxAutor.addItem("Todos");
//        for (Autor autor : listaView.getEstoqueComboBox().getMaterialComboBox().getAutores()) {
//            jComboBoxAutor.addItem(autor);
//        }
//
//        jComboBoxEditora.addItem("Todos");
//        for (Editora editora : listaView.getEstoqueComboBox().getMaterialComboBox().getEditoras()) {
//            jComboBoxEditora.addItem(editora);
//        }
//
//        jComboBoxCategoria.addItem("Todos");
//        for (Categoria categoria : listaView.getEstoqueComboBox().getMaterialComboBox().getCategorias()) {
//            jComboBoxCategoria.addItem(categoria);
//        }
//
//        jComboBoxPublico.addItem("Todos");
//        for (Publico publico : listaView.getEstoqueComboBox().getMaterialComboBox().getPublicos()) {
//            jComboBoxPublico.addItem(publico);
//        }
//
//        jComboBoxFormato.addItem("Todos");
//        for (Formato formato : listaView.getEstoqueComboBox().getMaterialComboBox().getFormatos()) {
//            jComboBoxFormato.addItem(formato);
//        }
//
//        jComboBoxStatu.addItem("Todos");
//        for (Statu statu : listaView.getEstoqueComboBox().getStatus()) {
//            jComboBoxStatu.addItem(statu);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCidadao = new javax.swing.JLabel();
        jComboBoxCodigo = new javax.swing.JComboBox();
        jLabelEstoque = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jCheckBoxAberto = new javax.swing.JCheckBox();
        jCheckBoxConcluido = new javax.swing.JCheckBox();
        jComboBoxEstoque = new javax.swing.JComboBox();
        jComboBoxCidadao = new javax.swing.JComboBox();

        setTitle("Filtro");
        setResizable(false);

        jLabelCidadao.setText("Cidadão");

        jComboBoxCodigo.setEditable(true);

        jLabelEstoque.setText("Estoque");

        jLabelCodigo.setText("Codigo");

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jCheckBoxAberto.setText("Aberto");
        jCheckBoxAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAbertoActionPerformed(evt);
            }
        });

        jCheckBoxConcluido.setText("Concluido");

        jComboBoxEstoque.setEditable(true);

        jComboBoxCidadao.setEditable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCidadao)
                            .addComponent(jLabelCodigo)
                            .addComponent(jLabelEstoque))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jComboBoxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jCheckBoxAberto)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxConcluido)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(125, Short.MAX_VALUE)
                    .addComponent(jComboBoxEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jComboBoxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidadao)
                    .addComponent(jComboBoxCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxAberto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxConcluido)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPesquisar)
                            .addComponent(jButtonCancelar)
                            .addComponent(jButtonLimpar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jComboBoxEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
//        jTextFieldTitulo.setText(null);
//        jTextFieldDescricao.setText(null);
//        jComboBoxCodigo.setSelectedIndex(0);
//        jComboBoxAnoPublicacao.setSelectedIndex(0);
//        jComboBoxAutor.setSelectedIndex(0);
//        jComboBoxEditora.setSelectedIndex(0);
//        jComboBoxCategoria.setSelectedIndex(0);
//        jComboBoxPublico.setSelectedIndex(0);
//        jComboBoxFormato.setSelectedIndex(0);
//        jComboBoxStatu.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
//        Estoque estoque = new Estoque();
//        Material material = new Material();
//        DadoMaterial dadoMaterial = new DadoMaterial();
//        if (!jTextFieldTitulo.getText().isEmpty()) {
//            dadoMaterial.setTitulo(jTextFieldTitulo.getText());
//        }
//        if (!jTextFieldDescricao.getText().isEmpty()) {
//            dadoMaterial.setDescricao(jTextFieldDescricao.getText());
//        }
//        if (jComboBoxCodigo.getSelectedIndex() > 0) {
//            dadoMaterial.setEdicao((Edicao) jComboBoxCodigo.getSelectedItem());
//        }
//        if (jComboBoxAnoPublicacao.getSelectedIndex() > 0) {
//            dadoMaterial.setAnoPublicacao((AnoPublicacao) jComboBoxAnoPublicacao.getSelectedItem());
//        }
//        if (jComboBoxEditora.getSelectedIndex() > 0) {
//            dadoMaterial.setEditora((Editora) jComboBoxEditora.getSelectedItem());
//        }
//        if (jComboBoxCategoria.getSelectedIndex() > 0) {
//            dadoMaterial.setCategoria((Categoria) jComboBoxCategoria.getSelectedItem());
//        }
//        if (jComboBoxPublico.getSelectedIndex() > 0) {
//            dadoMaterial.setPublico((Publico) jComboBoxPublico.getSelectedItem());
//        }
//        material.setDadoMaterial(dadoMaterial);
//        if (jComboBoxFormato.getSelectedIndex() > 0) {
//            material.setFormato((Formato) jComboBoxFormato.getSelectedItem());
//        }
//        estoque.setMaterial(material);
//        if (jComboBoxStatu.getSelectedIndex() > 0) {
//            estoque.setStatu((Statu) jComboBoxStatu.getSelectedItem());
//        }
//        listaView.getEstoquesController().filtrar(estoque);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jCheckBoxAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAbertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAbertoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JCheckBox jCheckBoxAberto;
    private javax.swing.JCheckBox jCheckBoxConcluido;
    private javax.swing.JComboBox jComboBoxCidadao;
    private javax.swing.JComboBox jComboBoxCodigo;
    private javax.swing.JComboBox jComboBoxEstoque;
    private javax.swing.JLabel jLabelCidadao;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelEstoque;
    // End of variables declaration//GEN-END:variables
}
