package com.live.adsfatene.biblioteca_publica.views.cidadaos;

import com.live.adsfatene.biblioteca_publica.models.Bairro;
import javax.swing.table.DefaultTableModel;
import com.live.adsfatene.biblioteca_publica.models.Celular;
import com.live.adsfatene.biblioteca_publica.models.Cidadao;
import com.live.adsfatene.biblioteca_publica.models.Cidade;
import com.live.adsfatene.biblioteca_publica.models.Estado;
import com.live.adsfatene.biblioteca_publica.models.Telefone;
import java.util.LinkedList;
import javax.swing.JOptionPane;

public class CadastroView extends javax.swing.JDialog {

    private final ListaView listaView;
    private final DefaultTableModel dtm;

    CadastroView(ListaView listaView, boolean modal) {
        super(listaView.getCidadaosController().getAplicacaoController().getAplicacaoView(), modal);
        initComponents();
        this.listaView = listaView;
        dtm = (DefaultTableModel) jTableCelulares.getModel();
        jComboBoxBairro.setEditable(true);
        jComboBoxCidade.setEditable(true);
    }

    @Override
    public void setVisible(boolean flag) {
        if (flag) {
            jButtonLimparActionPerformed(null);
            setLocationRelativeTo(listaView.getCidadaosController().getAplicacaoController().getAplicacaoView());
        }
        listaView.getjToggleButtonCadastro().setSelected(flag);
        super.setVisible(flag);
    }

    public void atualizar() {
        jComboBoxBairro.removeAllItems();
        jComboBoxCidade.removeAllItems();
        jComboBoxEstadoUF.removeAllItems();

        jTextFieldLogradouro.setText(null);
        jTextFieldNomeCompleto.setText(null);
        jTextFieldNumero.setText(null);

        for (Bairro bairro : listaView.getCidadaoComboBox().getBairros()) {
            jComboBoxBairro.addItem(bairro);
        }

        for (Cidade cidade : listaView.getCidadaoComboBox().getCidades()) {
            jComboBoxCidade.addItem(cidade);
        }

        for (Estado estado : listaView.getCidadaoComboBox().getEstados()) {
            jComboBoxEstadoUF.addItem(estado);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonCancelar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonRemoverTelefone = new javax.swing.JButton();
        jButtonAdicionarTefone = new javax.swing.JButton();
        jComboBoxBairro = new javax.swing.JComboBox();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelLogradouro = new javax.swing.JLabel();
        jLabelNomeCompleto = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCelulares = new javax.swing.JTable();
        jComboBoxEstadoUF = new javax.swing.JComboBox();
        jComboBoxCidade = new javax.swing.JComboBox();
        jButtonAdicionarCelular = new javax.swing.JButton();
        jButtonRemoverCelular = new javax.swing.JButton();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jLabeCelulares = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelEstadoUF = new javax.swing.JLabel();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jLabelTelefones = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTelefones = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Cadastro");
        setResizable(false);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonRemoverTelefone.setText("-");
        jButtonRemoverTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverTelefoneActionPerformed(evt);
            }
        });

        jButtonAdicionarTefone.setText("+");
        jButtonAdicionarTefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarTefoneActionPerformed(evt);
            }
        });

        jComboBoxBairro.setEditable(true);

        jLabelLogradouro.setText("Logradouro");

        jLabelNomeCompleto.setText("Nome Completo");

        jLabelBairro.setText("Bairro");

        jTableCelulares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Telefone", "DDD", "Número", "Estado - UF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableCelulares);

        jComboBoxCidade.setEditable(true);

        jButtonAdicionarCelular.setText("+");
        jButtonAdicionarCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarCelularActionPerformed(evt);
            }
        });

        jButtonRemoverCelular.setText("-");
        jButtonRemoverCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverCelularActionPerformed(evt);
            }
        });

        jTextFieldNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCompletoActionPerformed(evt);
            }
        });

        jLabeCelulares.setText("Celulares");

        jLabelCidade.setText("Cidade");

        jLabelEstadoUF.setText("Estado - UF");

        jLabelTelefones.setText("Telefones");

        jLabelNumero.setText("Nº");

        jTableTelefones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Telefone", "DDD", "Número", "Estado - UF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableTelefones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabeCelulares, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAdicionarCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonRemoverCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelNomeCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEstadoUF, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jLabelCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jLabelBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jLabelLogradouro, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jLabelNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxCidade, 0, 304, Short.MAX_VALUE)
                                    .addComponent(jComboBoxEstadoUF, 0, 304, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonAdicionarTefone, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonRemoverTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jTextFieldNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeCompleto)
                    .addComponent(jTextFieldNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstadoUF)
                    .addComponent(jComboBoxEstadoUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairro)
                    .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogradouro)
                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefones)
                    .addComponent(jButtonAdicionarTefone)
                    .addComponent(jButtonRemoverTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAdicionarCelular)
                        .addComponent(jButtonRemoverCelular))
                    .addComponent(jLabeCelulares, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldNomeCompleto.setText("");
        jTextFieldLogradouro.setText("");
        jTextFieldNumero.setText("");
        jComboBoxEstadoUF.setSelectedIndex(0);
        jComboBoxCidade.setSelectedIndex(0);
        jComboBoxBairro.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (jTextFieldNomeCompleto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "nome completo obrigatorio", "aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            Cidadao cidadao = new Cidadao();
            cidadao.setNomeCompleto(jTextFieldNomeCompleto.getText());
            cidadao.setLogradouro(jTextFieldLogradouro.getText());
            cidadao.setNumeroImovel(Integer.valueOf(jTextFieldNumero.getText()));

            Bairro bairro;
            if (jComboBoxBairro.getSelectedItem() instanceof Bairro) {
                bairro = ((Bairro) jComboBoxBairro.getSelectedItem()).getClone();
            } else {
                bairro = new Bairro();
                bairro.setNome(jComboBoxBairro.getSelectedItem().toString());
            }
            cidadao.setBairro(bairro);

            Cidade cidade;
            if (jComboBoxCidade.getSelectedItem() instanceof Cidade) {
                cidade = ((Cidade) jComboBoxCidade.getSelectedItem()).getClone();
            } else {
                cidade = new Cidade();
                cidade.setNome((String) jComboBoxCidade.getSelectedItem());
            }
            bairro.setCidade(cidade);

            cidade.setEstado((Estado) jComboBoxEstadoUF.getSelectedItem());

            cidadao.setTelefones(new LinkedList<Telefone>());
            cidadao.setCelulares(new LinkedList<Celular>());

            listaView.getCidadaosController().salvar(cidadao);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonRemoverTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverTelefoneActionPerformed
//        while (jTableFormato.getSelectedRowCount() > 0) {
//            jComboBoxFormato.addItem(dtm.getValueAt(jTableFormato.getSelectedRow(), 0));
//            dtm.removeRow(jTableFormato.getSelectedRow());
//        }
    }//GEN-LAST:event_jButtonRemoverTelefoneActionPerformed

    private void jButtonAdicionarTefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarTefoneActionPerformed
//        Formato formato;
//        if (jComboBoxFormato.getSelectedItem() instanceof Formato) {
//            formato = (Formato) jComboBoxFormato.getSelectedItem();
//            jComboBoxFormato.removeItemAt(jComboBoxFormato.getSelectedIndex());
//        } else {
//            formato = new Formato();
//            formato.setNome(jComboBoxFormato.getSelectedItem().toString());
//            jComboBoxFormato.setSelectedIndex(0);
//        }
//
//        int quantidade = 1;
//        if (formato.getNome().equalsIgnoreCase("impresso")) {
//            String valor = JOptionPane.showInputDialog(this, "digite uma quantidade:", "Quantidade", JOptionPane.INFORMATION_MESSAGE);
//            try {
//                quantidade = Integer.valueOf(valor);
//                if (quantidade < 1) {
//                    quantidade = 1;
//                }
//            } catch (NumberFormatException ex) {
//                quantidade = 1;
//            }
//        }
//        dtm.addRow(new Object[dtm.getColumnCount()]);
//        dtm.setValueAt(formato, dtm.getRowCount() - 1, 0);
//        dtm.setValueAt(quantidade, dtm.getRowCount() - 1, 1);
//        dtm.setValueAt("", dtm.getRowCount() - 1, 2);
//        dtm.setValueAt("", dtm.getRowCount() - 1, 3);
    }//GEN-LAST:event_jButtonAdicionarTefoneActionPerformed

    private void jButtonAdicionarCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdicionarCelularActionPerformed

    private void jButtonRemoverCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoverCelularActionPerformed

    private void jTextFieldNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCompletoActionPerformed
    }//GEN-LAST:event_jTextFieldNomeCompletoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarCelular;
    private javax.swing.JButton jButtonAdicionarTefone;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonRemoverCelular;
    private javax.swing.JButton jButtonRemoverTelefone;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxBairro;
    private javax.swing.JComboBox jComboBoxCidade;
    private javax.swing.JComboBox jComboBoxEstadoUF;
    private javax.swing.JLabel jLabeCelulares;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelEstadoUF;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelNomeCompleto;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelTelefones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableCelulares;
    private javax.swing.JTable jTableTelefones;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
