package com.live.adsfatene.biblioteca_publica.views;

import com.live.adsfatene.biblioteca_publica.controllers.AplicacaoController;
import java.sql.SQLException;
import javax.swing.JFrame;

public class AplicacaoView extends javax.swing.JFrame {

    private final AplicacaoController aplicacaoController;
    private final SobreView sobreView;

    public AplicacaoView(AplicacaoController aplicacaoController) {
        initComponents();
        this.aplicacaoController = aplicacaoController;
        sobreView = new SobreView(this, true);
        sobreView.setResizable(false);
        sobreView.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuItemInicio = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMateriais = new javax.swing.JMenuItem();
        jMenuItemEstoques = new javax.swing.JMenuItem();
        jMenuItemCidadaos = new javax.swing.JMenuItem();
        jMenuItemEmprestimos = new javax.swing.JMenuItem();
        jMenuItemEstoquesDanificados = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenuOpcoes.setText("Opções");

        jMenuItemInicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemInicio.setText("Início");
        jMenuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInicioActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemInicio);
        jMenuOpcoes.add(jSeparator1);

        jMenuItemMateriais.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemMateriais.setText("Materiais");
        jMenuItemMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMateriaisActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemMateriais);

        jMenuItemEstoques.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemEstoques.setText("Estoques");
        jMenuItemEstoques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstoquesActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemEstoques);

        jMenuItemCidadaos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemCidadaos.setText("Cidadãos");
        jMenuItemCidadaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCidadaosActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCidadaos);

        jMenuItemEmprestimos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemEmprestimos.setText("Emprestimos");
        jMenuItemEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmprestimosActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemEmprestimos);

        jMenuItemEstoquesDanificados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItemEstoquesDanificados.setText("Estoques Danificados");
        jMenuItemEstoquesDanificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstoquesDanificadosActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemEstoquesDanificados);
        jMenuOpcoes.add(jSeparator2);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemSair);

        jMenuBar1.add(jMenuOpcoes);

        jMenuAjuda.setText("Ajuda");

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMateriaisActionPerformed
        aplicacaoController.getMateriaisController().iniciar();
    }//GEN-LAST:event_jMenuItemMateriaisActionPerformed

    private void jMenuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInicioActionPerformed
        aplicacaoController.iniciar();
    }//GEN-LAST:event_jMenuItemInicioActionPerformed

    @Override
    public void dispose() {
        try {
            aplicacaoController.getConexao().getConnection().close();
        } catch (SQLException ex) {
            throw new RuntimeException(ex.getMessage());
        } finally {
            super.dispose();
        }
    }

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        sobreView.setLocationRelativeTo(this);
        sobreView.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemEstoquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstoquesActionPerformed
        aplicacaoController.getEstoquesController().iniciar();
    }//GEN-LAST:event_jMenuItemEstoquesActionPerformed

    private void jMenuItemEstoquesDanificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstoquesDanificadosActionPerformed
        aplicacaoController.getEmprestimosIrrecuperaveisController().iniciar();
    }//GEN-LAST:event_jMenuItemEstoquesDanificadosActionPerformed

    private void jMenuItemCidadaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCidadaosActionPerformed
        aplicacaoController.getCidadaosController().iniciar();
    }//GEN-LAST:event_jMenuItemCidadaosActionPerformed

    private void jMenuItemEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmprestimosActionPerformed
        aplicacaoController.getEmprestimosController().iniciar();
    }//GEN-LAST:event_jMenuItemEmprestimosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCidadaos;
    private javax.swing.JMenuItem jMenuItemEmprestimos;
    private javax.swing.JMenuItem jMenuItemEstoques;
    private javax.swing.JMenuItem jMenuItemEstoquesDanificados;
    private javax.swing.JMenuItem jMenuItemInicio;
    private javax.swing.JMenuItem jMenuItemMateriais;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables

    public void habilitar(boolean aFlag){
        jMenuOpcoes.setEnabled(aFlag);
    }
}